// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBancodeSangre.DAL;

#nullable disable

namespace SistemaBancodeSangre.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707172348_PRUEBA")]
    partial class PRUEBA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntregaEntitySolicitudEntity", b =>
                {
                    b.Property<int>("EntregasID")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudesID")
                        .HasColumnType("int");

                    b.HasKey("EntregasID", "SolicitudesID");

                    b.HasIndex("SolicitudesID");

                    b.ToTable("EntregaEntitySolicitudEntity");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.AnalisisEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Arritmias")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancer")
                        .HasColumnType("bit");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("Hemofilia")
                        .HasColumnType("bit");

                    b.Property<bool>("HipertensionAlterial")
                        .HasColumnType("bit");

                    b.Property<int>("MuestraID")
                        .HasColumnType("int");

                    b.Property<string>("Tipodesangre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Vhsida")
                        .HasColumnType("bit");

                    b.Property<string>("analista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("chagas")
                        .HasColumnType("bit");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaAnalisis")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hepatitisBoC")
                        .HasColumnType("bit");

                    b.Property<bool>("insuficienciaCardiaca")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MuestraID");

                    b.ToTable("Analisis");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.CitasEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("DonantesEntityID")
                        .HasColumnType("int");

                    b.Property<int>("DonantesID")
                        .HasColumnType("int");

                    b.Property<string>("NombreDonante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DonantesEntityID");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonacionesEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DonanteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDonacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventarioID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("analista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("cantidadSangre")
                        .HasColumnType("float");

                    b.Property<string>("envase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proposito")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("tipoDeSangre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ID");

                    b.HasIndex("DonanteID");

                    b.HasIndex("InventarioID");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonantesEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Edad")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("EmpleadosID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PesoKlg")
                        .HasColumnType("float");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoDeSangre")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipodeDonante")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EmpleadosID");

                    b.ToTable("Donantes");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.EmpleadosEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dirreccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.EntregaEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DonanteID")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fechaentrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudID")
                        .HasColumnType("int");

                    b.Property<double>("cantidadEntregada")
                        .HasColumnType("float");

                    b.Property<string>("tipoDeSangre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.InventarioEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DonacionesID")
                        .HasColumnType("int");

                    b.Property<string>("TipoSangre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaVencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.MuestraEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ApellidoDoante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoMuestra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonanteID")
                        .HasColumnType("int");

                    b.Property<string>("NombreDonante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSangre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("cantidadM")
                        .HasColumnType("float");

                    b.Property<string>("edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaToma")
                        .HasColumnType("datetime2");

                    b.Property<double>("presionAlterial")
                        .HasColumnType("float");

                    b.Property<double>("pulso")
                        .HasColumnType("float");

                    b.Property<string>("sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("temperatura")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DonanteID");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.ProcesamientoDeSangreEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Almacenado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonacionesID")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("estadoProceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaProceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("tipodeSangre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("volumenDN")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DonacionesID")
                        .IsUnique();

                    b.ToTable("Procesamientos");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.SolicitudEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<double>("cantidad")
                        .HasColumnType("float");

                    b.Property<string>("cartaMedica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("estadoSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exequatur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaDeSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("hospital")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("medico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("prioridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proposito")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("solicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipoDeSangresolicitada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.UsuariosEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("clave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("EmpleadoID")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EntregaEntitySolicitudEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.EntregaEntity", null)
                        .WithMany()
                        .HasForeignKey("EntregasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBancodeSangre.Entities.SolicitudEntity", null)
                        .WithMany()
                        .HasForeignKey("SolicitudesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.AnalisisEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.MuestraEntity", "Muestra")
                        .WithMany("Analisis")
                        .HasForeignKey("MuestraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.CitasEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.DonantesEntity", "DonantesEntity")
                        .WithMany("Citas")
                        .HasForeignKey("DonantesEntityID");

                    b.Navigation("DonantesEntity");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonacionesEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.DonantesEntity", "Donante")
                        .WithMany("Donaciones")
                        .HasForeignKey("DonanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBancodeSangre.Entities.InventarioEntity", "Inventario")
                        .WithMany("donaciones")
                        .HasForeignKey("InventarioID");

                    b.Navigation("Donante");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonantesEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.EmpleadosEntity", "Empleados")
                        .WithMany("Donantes")
                        .HasForeignKey("EmpleadosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.EntregaEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.EmpleadosEntity", "Empleado")
                        .WithMany("Entregas")
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.MuestraEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.DonantesEntity", "Donante")
                        .WithMany("Muestra")
                        .HasForeignKey("DonanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donante");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.ProcesamientoDeSangreEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.DonacionesEntity", "Donaciones")
                        .WithOne("ProcesamientoDeSangreEntity")
                        .HasForeignKey("SistemaBancodeSangre.Entities.ProcesamientoDeSangreEntity", "DonacionesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.UsuariosEntity", b =>
                {
                    b.HasOne("SistemaBancodeSangre.Entities.EmpleadosEntity", "Empleados")
                        .WithOne("Usuarios")
                        .HasForeignKey("SistemaBancodeSangre.Entities.UsuariosEntity", "EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonacionesEntity", b =>
                {
                    b.Navigation("ProcesamientoDeSangreEntity");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.DonantesEntity", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Donaciones");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.EmpleadosEntity", b =>
                {
                    b.Navigation("Donantes");

                    b.Navigation("Entregas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.InventarioEntity", b =>
                {
                    b.Navigation("donaciones");
                });

            modelBuilder.Entity("SistemaBancodeSangre.Entities.MuestraEntity", b =>
                {
                    b.Navigation("Analisis");
                });
#pragma warning restore 612, 618
        }
    }
}
